# Site settings
title: Jinu Daniel | ML Enthusiast
description: " A blog which will help you get acquainted with Data Science and Machine Learning"
url: "http://jinudaniel.github.io"
author:
  name: "Jacopo Rabolini"
  email: "hello@jacoporabolini.com"
  url: "http://www.jacoporabolini.com"


# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: false
reverse: false
